config/routes.rb
Tracknwin::Application.routes.draw do
  get "stats/index"

  resources :users do
	resources :rides
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :friends, :controller => 'friendships', :except => [:show, :edit]
  resources :microposts, only: [:create, :destroy]
  
  root to: 'static_pages#home'
  
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/androidlogin', to: 'users#androidlogin'
  match '/androidregister', to: 'users#androidregister'
  match '/androidaddride', to: 'rides#androidaddride'
  match '/rides/:id' => 'rides#show'
  match '/stats' => 'stats#index'
  post 'users/search'
  post 'microposts/create'
  post 'stats/create'
  post 'stats/index'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  if signed_in?
  redirect_to current_user
  end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About...') %>
<h1>About...</h1>
<p>
  The Tracknwin project was entirely designed and implemented by <a href="http://adriankuciel.pl">Adrian Kuciel</a> - student of Human–computer interaction on Jagiellonian University for his Bachelor's degree.
</p>
</br>
<h5>Technologies incorporated:</h5>
<ol>Rails 3.0</ol>
<ol>Java</ol>
<ol>JavaScript (jQuery)</ol>
<ol>CSS 3</ol>
<ol>Bootstrap</ol>
<h5>Tools used:</h5>
<ol>Notepad++</ol>
<ol>Eclipse juno</ol>
<ol>Adobe Photoshop CS6</ol>
<ol>Eldorado mini icons set</ol>
<h5>Title photo:</h5>
<ol><a href="http://oldtimewallpapers.com/en/motorcycles/original_9153_Bicycle-near-the-wall.html">"Bicycle near wall"</a> - free wallpaper from www.oldtimewallpapers.com</ol>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  If you noticed any bugs or errors please contact me <a href="mailto:djmicros@gmail.com">Here</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  To start using Tracknwin simply <%= link_to "Sign up!", signup_path%> by providing all the required data, then find our Android Application on app store and install it on your smartphone.
  After signing in on your phone, you will be able to start tracking your rides.
  Visit this site, sign in and check your recent rides, compare with friends and win prizes in monthly organized Tournaments.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit hero-bg">
<div class="hero-title">
  <h1>Welcome to the Tracknwin!</h1>
</br>
</br>
  <h3>
    Track, store and analyze your bike rides, find friends and win prizes!
  </h3>
</br>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  </br>
    </br>
  <p class="small">Already registered? <%= link_to "Sign in!", signin_path%></p>
</div>
</div>