config/routes.rb
Tracknwin::Application.routes.draw do
  get "stats/index"

  resources :users do
	resources :rides
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :friends, :controller => 'friendships', :except => [:show, :edit]
  resources :microposts, only: [:create, :destroy]
  
  root to: 'static_pages#home'
  
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/androidlogin', to: 'users#androidlogin'
  match '/androidregister', to: 'users#androidregister'
  match '/androidaddride', to: 'rides#androidaddride'
  match '/rides/:id' => 'rides#show'
  match '/stats' => 'stats#index'
  post 'users/search'
  post 'microposts/create'
  post 'stats/create'
  post 'stats/index'

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  
  def index
    @pending_requests = current_user.pending_invited_by
	@pending_invites = current_user.pending_invited
    @friends = current_user.friends

  end

  def new
    @users = User.all :conditions => ["id != ?", current_user.id]

  end

  def create
    invitee = User.find_by_id(params[:user_id])
    if current_user.invite invitee
	  flash[:success] = "Successfully invited friend!"
      redirect_to friends_path
    else
	  flash[:error] = "Sorry! You can't invite that user!"
      redirect_to friends_path
    end
  end

  def update
    inviter = User.find_by_id(params[:id])
    if current_user.approve inviter
	  current_user.microposts.create(:content => current_user.name + " became a friend with " + inviter.name + ".")
	  inviter.microposts.create(:content => inviter.name + " became a friend with " + current_user.name + ".")
	  flash[:success] = "Successfully confirmed friend!"
      redirect_to friends_path
    else
	  flash[:error] = "Sorry! Could not confirm friend!"
      redirect_to friends_path
    end
  end
  

  def destroy
    user = User.find_by_id(params[:id])
    if current_user.remove_friendship user
	  flash[:success] = "Successfully removed friend!"
      redirect_to friends_path
    else
	  flash[:error] = "Sorry, couldn't remove friend!"
      redirect_to friends_path
    end
  end 
  
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/index.html.erb
<% provide(:title, 'My friends') %>
<h1>My friends</h1>
<div class="tabbable"> 
  <ul class="nav nav-tabs">
    <li class="active"><a href="#friends" data-toggle="tab">My friends</a></li>
    <li><a href="#requests" data-toggle="tab">Requests</a></li>
	<li><a href="#invites" data-toggle="tab">My Invites</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="friends">
        <h4>My friends:</h4>
		<% if @friends != nil %>
		<% for i in (0..@friends.count-1) do %>
		<div id="friend" class="well">
		<%= gravatar_for @friends[i], size: 52 %>
		<%= link_to  :controller => "users", :action => "show", :id => @friends[i][:id] do %>
                  <%= @friends[i][:name] %>
		<% end %>
		</br>
		<%= link_to "Unfriend", friend_path(@friends[i][:id]), :method => "delete", class: "btn btn-small btn-danger", data: { confirm: "You sure?" } %>
		</br>
		</div>
		<% end %>
		<% else %>
			You have no friends.
		<% end %>
		</div>
    <div class="tab-pane" id="requests">
		<h4>People who invited you to become a friend:</h4>
		<% if @pending_requests != nil %>
		<% for i in (0..@pending_requests.count-1) do %>
		<div id="friend" class="well">
		<%= gravatar_for @pending_requests[i], size: 52 %>
		<%= link_to  :controller => "users", :action => "show", :id => @pending_requests[i][:id] do %>
                  <%= @pending_requests[i][:name] %>
		<% end %>
		</br>
		<%= link_to "Confirm", friend_path(@pending_requests[i][:id]), :method => "put", class: "btn btn-small btn-success" %>
		<%= link_to "Ignore", friend_path(@pending_requests[i][:id]), :method => "delete", class: "btn btn-small btn-danger" %>
		</br>
		</div>
		<% end %>
		<% else %>
			You have no requests.
		<% end %>
		</div>
	<div class="tab-pane" id="invites">
		<h4>People you invited:</h4>
		<% if @pending_invites != nil %>
		<% for i in (0..@pending_invites.count-1) do %>
		<div id="invite" class="well">
		<%= gravatar_for @pending_invites[i], size: 52 %>
		<%= link_to  :controller => "users", :action => "show", :id => @pending_invites[i][:id] do %>
                  <%= @pending_invites[i][:name] %>
		<% end %>
		</br>
		</br>
		</div>
		</br>
		<% end %>
		<% else %>
			You have not invited anyone yet.
		<% end %>
		</div>
		</div>
		</div>





app/views/friendships/invites.html.erb
<div id="invites" class="well well-large" >
	<h4>People you invited:</h4>
<% @pending_invites.each do |invite|%>

<%= link_to  :controller => "users", :action => "show", :id => invite[:id] do %>
                  <%= invite[:name] %>
<% end %>
</br>
<% end %>
</div>

app/views/friendships/new.html.erb
<%= link_to "Back to my Shelf", user_path(current_user),  class: "btn btn-small" %>

app/views/friendships/requests.html.erb
<div id="requests" class="well well-large" >
  <h4>People who invited you to become a friend:</h4>
  <% if @pending_requests.empty? != true %>
<% for i in (0..@pending_requests.count-1) do %>
<div id="friend" class="well">
  <%= gravatar_for @pending_requests[i], size: 52 %>
<%= link_to  :controller => "users", :action => "show", :id => @pending_requests[i][:id] do %>
                  <%= @pending_requests[i][:name] %>
<% end %>
</br>

<%= link_to "Confirm", friend_path(@pending_requests[i][:id]), :method => "put", class: "btn btn-small btn-success" %>

<%= link_to "Ignore", friend_path(@pending_requests[i][:id]), :method => "delete", class: "btn btn-small btn-danger" %>

</br>
</div>
<% end %>
<% else %>
You have no requests.
<% end %>
</div>