config/routes.rb
Tracknwin::Application.routes.draw do
  get "stats/index"

  resources :users do
	resources :rides
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :friends, :controller => 'friendships', :except => [:show, :edit]
  resources :microposts, only: [:create, :destroy]
  
  root to: 'static_pages#home'
  
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/androidlogin', to: 'users#androidlogin'
  match '/androidregister', to: 'users#androidregister'
  match '/androidaddride', to: 'rides#androidaddride'
  match '/rides/:id' => 'rides#show'
  match '/stats' => 'stats#index'
  post 'users/search'
  post 'microposts/create'
  post 'stats/create'
  post 'stats/index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
	Tracknwin by 
    <a href="http://adriankuciel.pl">Adrian Kuciel</a>
  </small>
  <nav>
    <ul>
		<li><%= link_to "About",   about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top ">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to (image_tag("logo.png", :alt => "tracknwin")), root_path, id: "logo" %>
       <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
			<li><%= link_to "Friends", friends_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sub-nav.html.erb
          <% if signed_in? %>
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
       <nav>
        <ul class="sub-nav">
		
		<li class="<%= "nav-active" if params[:controller] == "users" && params[:action] == "show" %>">
			<%= link_to current_user do%>
			<div class="batch">
			<i class="profile-icon"></i>
			<br>
			Profile
			</div>
			<% end %>
		</li>
		<li class="<%= "nav-active" if params[:controller] == "rides" && params[:action] == "index" %>">
			<%= link_to  :controller => :rides, :action => :index, :user_id => current_user.id do%>
				<div class="batch">
				<i class="rides-icon"></i>
				<br>
				Rides
				</div>
			<% end %>
		</li>
		<li class="<%= "nav-active" if params[:controller] == "stats" && params[:action] == "index" %>">
			<%= link_to stats_path do%>
				<div class="batch">
				<i class="stats-icon"></i>
				<br>
				Stats
				</div>
			<% end %>
		</li>
		<li class="<%= "nav-active" if params[:controller] == "users" && params[:action] == "index" %>">
			<%= link_to users_path do%>
				<div class="batch">
				<i class="users-icon"></i>
				<br>
				Users
				</div>
			<% end %>
		</li>
		<li class="<%= "nav-active" if params[:controller] == "friendships" %>">
			<%= link_to friends_path do%>
				<div class="batch">
				<% if current_user.pending_invited_by.empty? != true %>
				<div class="invite_notification label label-important pull-right">
				<%= current_user.pending_invited_by.count %>
				</div>
				<% end %>
				<i class="friends-icon"></i>
				<br>
				Friends
				</div>
			<% end %>
		</li>
		<li class="<%= "nav-active" if params[:controller] == "users" && params[:action] == "edit" %>">
			<%= link_to edit_user_path(current_user) do%>
				<div class="batch">
				<i class="settings-icon"></i>
				<br>
				Settings
				</div>
			<% end %>
		</li>
		<li>
			<%= link_to signout_path, method: "delete" do%>
				<div class="batch">
				<i class="signout-icon"></i>
				<br>
				Sign out
				</div>
			<% end %>
		</li> 
		  
              </ul>
            </li>
        </ul>
      </nav>
    </div>
  </div>
</div>
          <% else %>

          <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
	<%= render 'layouts/sub-nav' %>
    <div class="container <% if signed_in? %>well site-container <% end %> ">
	      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
	<%= render 'layouts/footer' %>
    </div>
	      <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/layouts/ride.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no"></meta>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>

	<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAj1VhTA5l4MKf9AloiQ81JkHvjXMedSI4&sensor=true">
    </script>  
	
  </head>
  <body>
    <%= render 'layouts/header' %>
	<%= render 'layouts/sub-nav' %>
    <div class="container <% if signed_in? %>well site-container <% end %> ">
	      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
	<%= render 'layouts/footer' %>
    </div>
	      <%= debug(params) if Rails.env.development? %>
  </body>
</html>